pds_insights_search.settings:
  type: config_object
  label: 'Principal: InsightsSearch (ajustes)'
  mapping:
    header:         { type: label,  label: 'Título' }
    header_accent:  { type: label,  label: 'Título destacado' }
    events_json:    { type: text,   label: 'Eventos (JSON)' }
    aria_label:     { type: label,  label: 'Etiqueta ARIA' }
    prev_label:     { type: label,  label: 'Etiqueta botón anterior' }
    next_label:     { type: label,  label: 'Etiqueta botón siguiente' }
