pds_image_text.settings:
  type: config_object
  label: 'Principal: Imagen y texto (ajustes)'
  mapping:
    header:         { type: label,  label: 'Título' }
    header_accent:  { type: label,  label: 'Título destacado' }
    description:    { type: text,   label: 'Descripción' }
    button_text:    { type: label,  label: 'Texto del botón' }
    button_url:     { type: string, label: 'URL del botón' }
    image_src:      { type: string, label: 'URL de imagen' }
    image_alt:      { type: label,  label: 'Alt de imagen' }
    image_position: { type: string, label: 'Posición (left/right)' }
    aria_label:     { type: label,  label: 'Etiqueta ARIA' }
